# Generated by Django 2.1.2 on 2018-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('no_hp', models.CharField(max_length=15)),
                ('usia', models.CharField(max_length=3)),
                ('alamat', models.CharField(max_length=255)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('hobi', models.CharField(max_length=100)),
            ],
        ),
    ]
