# Generated by Django 2.1.2 on 2018-10-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peserta',
            table='peserta',
        ),
    ]
