# Generated by Django 2.1.2 on 2018-10-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0002_auto_20181015_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='gender',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita'), ('Waria', 'Waria')], max_length=10),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='hobi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='usia',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
