# Generated by Django 2.1.2 on 2018-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0003_auto_20181015_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=100)),
                ('perusahaan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pekerjaan',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='peserta',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='peserta',
            name='pekerjaan',
            field=models.ForeignKey(null=True, on_delete=None, related_name='pesertas', to='peserta.Pekerjaan'),
        ),
    ]
